server:
  port: 8082

#logging:
#  level:
#    org.springframework: DEBUG

spring:
  application:
    name: multitenancy

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        multiTenancy: DATABASE

  datasource:
    tenant1:
      url: jdbc:postgresql://localhost:5433/customerdb
      username: admin
      password: root
      driver-class-name: org.postgresql.Driver
    tenant2:
      url: jdbc:postgresql://localhost:5433/customer2db
      username: admin
      password: root
      driver-class-name: org.postgresql.Driver
    tenant3:
      url: jdbc:postgresql://localhost:5433/customer3db
      username: admin
      password: root
      driver-class-name: org.postgresql.Driver